Repository zhamao-robot/zhamao-framework, pull requests merged in 2022-08, with the labels that each got.

#143 解决explode_msg中，传入参数为0时，参数0消失的BUG
  src/ZM/global_functions.php
Labels: bug, priority/medium

#144 fix container and coroutine bug
  composer.json
  phpstan.neon
  src/Globals/global_functions.php
  src/ZM/Container/ContainerServicesProvider.php
  src/ZM/Event/Listener/HttpEventListener.php
  src/ZM/Utils/ZMUtil.php
Labels: bug, priority/medium

#148 完善 MySQL 连接池和组件
  .github/workflows/integration-test.yml
  composer.json
  config/global.php
  src/Globals/global_functions.php
  src/ZM/Command/BotCraft/BotCraftCommand.php
  src/ZM/Command/Server/ServerStartCommand.php
  src/ZM/ConsoleApplication.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Framework.php
  src/ZM/Middleware/MiddlewareHandler.php
  src/ZM/Store/MySQL/MySQLConnection.php
  src/ZM/Store/MySQL/MySQLDriver.php
  src/ZM/Store/MySQL/MySQLException.php
  src/ZM/Store/MySQL/MySQLPool.php
  src/ZM/Store/MySQL/MySQLQueryBuilder.php
  src/ZM/Store/MySQL/MySQLStatement.php
  src/ZM/Store/MySQL/MySQLStatementWrapper.php
  src/ZM/Store/MySQL/MySQLWrapper.php
  tests/ZM/Utils/ZMUtilTest.php
Labels: enhancement, priority/medium

#150 修复 gendoc 不兼容
  bin/gendoc
  composer.json
Labels: bug, priority/medium

#149 添加类别名
  composer.json
  src/Globals/global_class_alias.php
  src/ZM/Annotation/AnnotationBase.php
  src/ZM/Annotation/Middleware/HandleAfter.php
  src/ZM/Annotation/Middleware/HandleBefore.php
  src/ZM/Annotation/Middleware/HandleException.php
  src/ZM/Annotation/Middleware/MiddlewareClass.php
  src/ZM/InstantApplication.php
Labels: enhancement

#151 修复对 Windows 环境开发的支持
  src/ZM/Framework.php
  src/ZM/Store/FileSystem.php
  src/ZM/Store/MySQL/MySQLConnection.php
  zhamao-server.bat
  zhamao.bat
Labels: bug

#152 add phpunit windows support
  .github/workflows/integration-test.yml
  bin/phpunit-zm
  bin/phpunit-zm.bat
  config/global.php
  src/ZM/Annotation/AnnotationHandler.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Framework.php
  src/ZM/Process/ProcessStateManager.php
  src/ZM/Store/MockAtomic.php
  tests/ZM/Middleware/PipelineTest.php
Labels: enhancement, priority/medium

#146 基于 LibOB Config 类重构 ZMConfig
  src/Globals/global_functions.php
  src/ZM/Annotation/AnnotationParser.php
  src/ZM/Command/CheckConfigCommand.php
  src/ZM/Command/Generate/SystemdGenerateCommand.php
  src/ZM/Config/ConfigMetadata.php
  src/ZM/Config/ZMConfig.php
  src/ZM/Container/ContainerServicesProvider.php
  src/ZM/Event/Listener/MasterEventListener.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Exception/ConfigException.php
  src/ZM/Framework.php
  src/ZM/InstantApplication.php
  src/ZM/Store/MySQL/MySQLDriver.php
  src/ZM/Utils/HttpUtil.php
  src/ZM/Utils/ReflectionUtil.php
  tests/ZM/Config/ZMConfigTest.php
  tests_old/ZM/Config/ZMConfigTest.php
Labels: enhancement, wip, priority/medium

#160 Sqlite 支持
  .github/workflows/integration-test.yml
  bin/phpunit-zm
  composer.json
  config/global.php
  src/Globals/global_functions.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Store/Database/DBConnection.php
  src/ZM/Store/Database/DBException.php
  src/ZM/Store/Database/DBPool.php
  src/ZM/Store/Database/DBQueryBuilder.php
  src/ZM/Store/Database/DBStatement.php
  src/ZM/Store/Database/DBStatementWrapper.php
  src/ZM/Store/Database/DBWrapper.php
  src/ZM/Store/Database/MySQLDriver.php
  src/ZM/Store/Database/SQLiteDriver.php
  src/ZM/Store/MySQL/MySQLException.php
Labels: enhancement, priority/medium

#161 修复 Framework 中 Config 重写的 Bug
  src/ZM/Framework.php
Labels: bug, priority/urgent

#162 FileSystem.php isRelativePath() 对 Windows 的兼容性
  src/ZM/Store/FileSystem.php
Labels: bug, priority/medium
