Repository zhamao-robot/zhamao-framework, pull requests merged in 2022-12, with the labels that each got.

#176 增加 Docker Compose 支持
  composer.json
  docker-compose.yml
  docker/.gitignore
  docker/environment.env.example
  docker/walle-q/Dockerfile
  docker/zhamao/Dockerfile
  src/Globals/global_defines_app.php
  src/ZM/Command/Command.php
  src/ZM/Command/InitCommand.php
  src/ZM/ConsoleApplication.php
  src/ZM/Exception/InitException.php
  src/ZM/Exception/SingletonViolationException.php
  src/ZM/Framework.php
  src/ZM/InstantApplication.php
Labels: enhancement

#178 添加贡献指南
  CONTRIBUTING.md
Labels: documentation

#179 迁移 Symfony Console V6
  src/ZM/Command/BotCraft/BotCraftCommand.php
  src/ZM/Command/BuildCommand.php
  src/ZM/Command/CheckConfigCommand.php
  src/ZM/Command/Command.php
  src/ZM/Command/Generate/SystemdGenerateCommand.php
  src/ZM/Command/InitCommand.php
  src/ZM/Command/NonPharLoadModeOnly.php
  src/ZM/Command/ProxyServerCommand.php
  src/ZM/Command/ReplCommand.php
  src/ZM/Command/Server/ServerReloadCommand.php
  src/ZM/Command/Server/ServerStartCommand.php
  src/ZM/Command/Server/ServerStatusCommand.php
  src/ZM/Command/Server/ServerStopCommand.php
  src/ZM/Command/SourceLoadModeOnly.php
  src/ZM/ConsoleApplication.php
Labels: improvement

#181 兼容 8.x PHP 一些改动
  .run/Reload Zhamao Server.run.xml
  .run/Run Zhamao Server.run.xml
  .run/Run watcher.run.xml
  .run/Stop Zhamao Server.run.xml
  composer.json
  config/logging.php
  ext/go.sh
  instant-plugin-demo.php
  mybot.php
  src/Globals/global_class_alias.php
  src/ZM/Annotation/AnnotationHandler.php
  src/ZM/Annotation/AnnotationMap.php
  src/ZM/Annotation/AnnotationParser.php
  src/ZM/Annotation/Framework/BindEvent.php
  src/ZM/Annotation/Framework/Init.php
  src/ZM/Annotation/Http/Controller.php
  src/ZM/Annotation/Http/Route.php
  src/ZM/Annotation/Middleware/Middleware.php
  src/ZM/Annotation/OneBot/BotCommand.php
  src/ZM/Event/Listener/HttpEventListener.php
  src/ZM/Framework.php
  src/ZM/Middleware/Pipeline.php
  src/ZM/Plugin/ZMPlugin.php
  src/ZM/Utils/EasterEgg.php
  src/ZM/ZMApplication.php
Labels: improvement

#180 升级部分依赖
  .github/workflows/coding-style.yml
  .github/workflows/increment-build-number.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  .github/workflows/vuepress-deploy.yml
Labels: improvement

#184 插件和 OneBot 12 适配器前置内容
  config/global.php
  src/ZM/Command/CheckConfigCommand.php
  src/ZM/Event/Listener/HttpEventListener.php
  src/ZM/Event/Listener/WSEventListener.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Exception/InitException.php
  src/ZM/Exception/PluginException.php
  src/ZM/Framework.php
  src/ZM/Plugin/OneBot12Adapter.php
  src/ZM/Plugin/PluginManager.php
  src/ZM/Utils/ConnectionUtil.php
  src/ZM/Utils/HttpUtil.php
Labels: enhancement, priority/medium

#185 完善插件加载系统
  .gitignore
  config/global.php
  instant-plugin-demo.php
  mybot.php
  src/Globals/global_class_alias.php
  src/Module/Example/Hello123.php
  src/ZM/Annotation/AnnotationBase.php
  src/ZM/Annotation/AnnotationHandler.php
  src/ZM/Annotation/AnnotationMap.php
  src/ZM/Annotation/AnnotationParser.php
  src/ZM/Annotation/OneBot/BotCommand.php
  src/ZM/Annotation/OneBot/CommandArgument.php
  src/ZM/Event/Listener/WSEventListener.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Exception/ZMKnownException.php
  src/ZM/Plugin/OneBot12Adapter.php
  src/ZM/Plugin/PluginManager.php
  src/ZM/Store/Database/DBException.php
  src/ZM/ZMApplication.php
Labels: enhancement

#186 更新 README 测试徽章路径
  README.md
Labels: documentation

#187 PHP80 小修
  src/Globals/global_defines_app.php
  src/Globals/global_functions.php
  src/ZM/Annotation/AnnotationBase.php
  src/ZM/Annotation/AnnotationHandler.php
  src/ZM/Annotation/AnnotationParser.php
  src/ZM/Annotation/Framework/BindEvent.php
  src/ZM/Annotation/Framework/Init.php
  src/ZM/Annotation/Http/Controller.php
  src/ZM/Annotation/Http/Route.php
  src/ZM/Annotation/Middleware/Middleware.php
  src/ZM/Annotation/OneBot/BotCommand.php
  src/ZM/Annotation/OneBot/BotEvent.php
  src/ZM/Annotation/OneBot/CommandArgument.php
  src/ZM/Command/CheckConfigCommand.php
  src/ZM/Command/InitCommand.php
  src/ZM/Command/ProxyServerCommand.php
  src/ZM/Command/Server/ServerStartCommand.php
  src/ZM/Command/Server/ServerStopCommand.php
  src/ZM/Config/ZMConfig.php
  src/ZM/ConsoleApplication.php
  src/ZM/Container/BoundMethod.php
  src/ZM/Container/ContainerTrait.php
  src/ZM/Event/EventProvider.php
  src/ZM/Event/Listener/SignalListener.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Exception/InterruptException.php
  src/ZM/Framework.php
  src/ZM/Middleware/MiddlewareHandler.php
  src/ZM/Middleware/Pipeline.php
  src/ZM/Process/ProcessStateManager.php
  src/ZM/Store/Database/DBConnection.php
  src/ZM/Store/Database/DBPool.php
  src/ZM/Store/Database/DBQueryBuilder.php
  src/ZM/Store/Database/DBStatement.php
  src/ZM/Store/Database/DBStatementWrapper.php
  src/ZM/Store/Database/DBWrapper.php
  src/ZM/Store/FileSystem.php
  src/ZM/Store/Lock/FileLock.php
  src/ZM/Utils/ConnectionUtil.php
  src/ZM/Utils/HttpUtil.php
  src/ZM/Utils/ReflectionUtil.php
  src/ZM/Utils/ZMUtil.php
  tests/ZM/Config/ZMConfigTest.php
  tests/ZM/Middleware/PipelineTest.php
  tests/ZM/Utils/ReflectionUtilTest.php
  tests/ZMResultPrinter.php
Labels: improvement

#193 改进测试运行
  composer.json
  phpstan.neon
  tests/TestCase.php
  tests/Trait/HasLogger.php
  tests/ZM/Config/ZMConfigTest.php
  tests/ZM/Middleware/PipelineTest.php
  tests/ZM/Utils/ReflectionUtilTest.php
  tests/ZM/Utils/ZMUtilTest.php
Labels: enhancement

#194 添加些许测试
  composer.json
  src/ZM/Store/FileSystem.php
  src/ZM/Utils/CatCode.php
  tests/Trait/HasLogger.php
  tests/Trait/HasVirtualFileSystem.php
  tests/ZM/Store/FileSystemTest.php
  tests/ZM/Utils/CatCodeTest.php
Labels: enhancement

#196 修复 getClassesPsr4 中默认过滤方法的路径 Bug
  .php-cs-fixer.php
  src/ZM/ConsoleApplication.php
  src/ZM/Utils/ZMUtil.php
  src/ZM/script_phar_stub.php
Labels: bug, priority/medium

#198 修复 getClassesPsr4 中默认过滤方法的路径 Bug
  src/ZM/Store/FileSystem.php
Labels: bug, priority/medium

#197 新增 CatCode encode 时选择是否编码文本的参数
  src/ZM/Utils/CatCode.php
  src/ZM/Utils/MessageUtil.php
Labels: improvement, priority/medium

#201 切换容器实现为 PHP-DI
  composer.json
  config/container.php
  src/Globals/global_class_alias.php
  src/Globals/global_class_alias_helper.php
  src/Globals/global_functions.php
  src/Module/Example/Hello123.php
  src/ZM/Command/Generate/ClassAliasHelperGenerateCommand.php
  src/ZM/Container/AliasDefinitionSource.php
  src/ZM/Container/BoundMethod.php
  src/ZM/Container/ClassAliasHelper.php
  src/ZM/Container/Container.php
  src/ZM/Container/ContainerBindingListener.php
  src/ZM/Container/ContainerHolder.php
  src/ZM/Container/ContainerInterface.php
  src/ZM/Container/ContainerRegistrant.php
  src/ZM/Container/ContainerServicesProvider.php
  src/ZM/Container/ContainerTrait.php
  src/ZM/Container/EntryNotFoundException.php
  src/ZM/Container/EntryResolutionException.php
  src/ZM/Container/WorkerContainer.php
  src/ZM/Event/Listener/HttpEventListener.php
  src/ZM/Event/Listener/WSEventListener.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Framework.php
  src/ZM/Middleware/MiddlewareHandler.php
  src/ZM/Plugin/OneBot12Adapter.php
Labels: improvement

#202 添加插件生成功能
  src/Templates/PluginMain.php.template
  src/Templates/main.php.template
  src/ZM/Command/Command.php
  src/ZM/Command/Plugin/PluginMakeCommand.php
  src/ZM/Store/FileSystem.php
  src/ZM/Utils/CodeGenerator/PluginGenerator.php
Labels: enhancement, priority/urgent

#203 完善 BotCommand 和 CommandArgument 的解析
  src/Globals/global_defines_app.php
  src/Globals/global_functions.php
  src/ZM/Annotation/AnnotationMap.php
  src/ZM/Annotation/OneBot/BotCommand.php
  src/ZM/Annotation/OneBot/CommandArgument.php
  src/ZM/Context/BotContext.php
  src/ZM/Exception/WaitTimeoutException.php
  src/ZM/Plugin/OneBot12Adapter.php
  src/ZM/Utils/CodeGenerator/PluginGenerator.php
  src/ZM/Utils/MessageUtil.php
Labels: enhancement, priority/urgent

#206 发布 beta2
  composer.json
  docs/.vuepress/config.js
  docs/guide/README.md
  docs/guide/installation.md
  src/ZM/Context/BotContext.php
  src/ZM/Framework.php
Labels: improvement, priority/urgent, documentation

#208 添加 Windows 入口
  bin/phpunit-zm
  bin/zhamao.bat
  composer.json
Labels: enhancement

#211 修复 BotContext 不同步问题
  src/Globals/global_functions.php
  src/ZM/Container/ContainerRegistrant.php
Labels: bug

#213 让容器支持协程
  src/ZM/Container/ContainerHolder.php
Labels: improvement

#214 拆分 Bot 动作到 Trait 以及更新一些类型强化的代码
  .gitignore
  config/global.php
  src/Globals/global_functions.php
  src/ZM/Context/BotContext.php
  src/ZM/Context/Trait/BotActionTrait.php
  src/ZM/Event/Listener/SignalListener.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Framework.php
  src/ZM/Utils/ZMUtil.php
  src/ZM/ZMApplication.php
Labels: improvement

#215 添加 v3 版本的一键安装脚本
  .github/workflows/vuepress-deploy.yml
  ext/v3.sh
Labels: enhancement

#216 新增 ZMRequest
  src/ZM/Framework.php
  src/ZM/Utils/ZMRequest.php
  tests/ZM/Utils/ZMRequestTest.php
Labels: enhancement

#217 新增全新的 LightCache
  config/global.php
  src/Globals/global_class_alias.php
  src/Globals/global_functions.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Store/KV/KVInterface.php
  src/ZM/Store/KV/LightCache.php
  tests/ZM/Store/KV/LightCacheTest.php
Labels: enhancement

#218 切换 Git Hook 至 Captainhook
  captainhook.json
  composer.json
Labels: improvement

#219 升级 v3 文档构建发布路径
  .github/workflows/vuepress-deploy.yml
  docs/README.md
Labels: documentation

#220 根据最新的分支命名更新 Workflows
  .github/workflows/increment-build-number.yml
  .github/workflows/vuepress-deploy.yml
Labels: improvement

#221 更新部分文档
  docs/guide/README.md
  docs/guide/get_started.md
  docs/guide/installation.md
  docs/guide/structure.md
Labels: documentation

#222 将 KV 库接口调整为 PSR-16
  composer.json
  config/container.php
  src/Globals/global_functions.php
  src/ZM/Store/KV/KVInterface.php
  src/ZM/Store/KV/LightCache.php
  tests/ZM/Store/KV/LightCacheTest.php
Labels: enhancement

#223 修复有关 BotCommand 的 Bug
  src/ZM/Annotation/AnnotationHandler.php
  src/ZM/Framework.php
  src/ZM/Plugin/OneBot12Adapter.php
Labels: bug

#224 边缘 Bug 修复
  src/ZM/Context/BotContext.php
  src/ZM/Event/Listener/HttpEventListener.php
Labels: bug
