Repository zhamao-robot/zhamao-framework, pull requests merged in 2022-05, with the labels that each got.

#112 修复 PHPUnit Printer
  bin/phpunit-swoole
  ext/lib/Printer.php
  ext/lib/Version.php
Labels: bug, priority/low

#111 新增 @CommandArgument 注解
  docs/guide/errcode.md
  src/Module/Example/Hello.php
  src/ZM/Annotation/AnnotationParser.php
  src/ZM/Annotation/CQ/CommandArgument.php
  src/ZM/Entity/InputArguments.php
  src/ZM/Event/EventManager.php
  src/ZM/Event/EventMapIterator.php
  src/ZM/Module/QQBot.php
  src/ZM/Utils/MessageUtil.php
  src/ZM/global_defines.php
Labels: enhancement, priority/medium

#110 重构 CommandHelpGenerator 至 CommandInfoUtil
  composer.json
  src/Module/Example/Hello.php
  src/ZM/Utils/CommandInfoUtil.php
  src/ZM/Utils/MessageUtil.php
  tests/ZM/Utils/CommandInfoUtilTest.php
  tests/ZM/Utils/MessageUtilTest.php
Labels: improvement, priority/medium

#114 2.8 补充特性更新
  .gitignore
  docs/guide/installation.md
  phpstan.neon
  src/ZM/API/CQ.php
  src/ZM/Command/RunServerCommand.php
  src/ZM/Event/EventDispatcher.php
  src/ZM/Event/EventMapIterator.php
  src/ZM/Framework.php
  src/ZM/Module/ModuleBase.php
  src/ZM/Module/ModuleUnpacker.php
  src/ZM/Utils/Terminal.php
  src/ZM/ZMServer.php
  src/ZM/global_functions.php
  src/ZM/script_phar_stub.php
  tests/ZM/Event/EventMapIteratorTest.php
  tests/ZM/Utils/TerminalTest.php
Labels: enhancement, priority/urgent

#115 添加 Macroable 测试
  tests/ZM/Utils/MacroableTest.php
Labels: enhancement, priority/low

#116 添加 ReflectionUtil 测试
  src/ZM/Utils/ReflectionUtil.php
  tests/ZM/Utils/ReflectionUtilTest.php
Labels: enhancement, priority/low

#119 添加 LightCache 測試
  tests/ZM/Store/LightCacheTest.php
Labels: enhancement, priority/low

#122 安装命令、操作命令强化
  .github/workflows/vuepress-deploy.yml
  README.md
  docs/README.md
  docs/guide/installation.md
  ext/go-cqhttp-down.sh
  ext/go.sh
  src/ZM/Command/Server/ServerStopCommand.php
Labels: enhancement, priority/urgent

#121 添加 Adapter 基础
  src/ZM/Adapters/AdapterInterface.php
  src/ZM/Adapters/OneBot11Adapter.php
  src/ZM/Event/EventDispatcher.php
  src/ZM/Event/SwooleEvent/OnWorkerStart.php
  src/ZM/Utils/ZMUtil.php
  src/ZM/global_functions.php
Labels: enhancement, priority/medium

#124 重构 ZMConfig
  composer.json
  docs/guide/errcode.md
  src/ZM/Config/ConfigMetadata.php
  src/ZM/Config/ZMConfig.php
  src/ZM/Event/SwooleEvent/OnWorkerStop.php
  src/ZM/Exception/ConfigException.php
  src/ZM/Framework.php
  src/ZM/Utils/DataProvider.php
  src/ZM/global_functions.php
  tests/ZM/Config/ZMConfigTest.php
  tests/ZM/Utils/HttpUtilTest.php
  tests/ZM/Utils/MessageUtilTest.php
Labels: enhancement, priority/medium

#125 框架V3部分重构
  bin/phpunit-swoole
  bin/start
  composer.json
  src/ZM/Command/Daemon/DaemonReloadCommand.php
  src/ZM/Command/Daemon/DaemonStatusCommand.php
  src/ZM/Command/Daemon/DaemonStopCommand.php
  src/ZM/Command/PureHttpCommand.php
  src/ZM/Command/Server/ServerCommand.php
  src/ZM/Command/Server/ServerReloadCommand.php
  src/ZM/Command/Server/ServerStartCommand.php
  src/ZM/Command/Server/ServerStatusCommand.php
  src/ZM/Command/Server/ServerStopCommand.php
  src/ZM/Config/ZMConfig.php
  src/ZM/ConsoleApplication.php
  src/ZM/Event/SwooleEvent/OnManagerStart.php
  src/ZM/Event/SwooleEvent/OnManagerStop.php
  src/ZM/Event/SwooleEvent/OnShutdown.php
  src/ZM/Event/SwooleEvent/OnStart.php
  src/ZM/Event/SwooleEvent/OnWorkerExit.php
  src/ZM/Event/SwooleEvent/OnWorkerStart.php
  src/ZM/Event/SwooleEvent/OnWorkerStop.php
  src/ZM/Framework.php
  src/ZM/Store/LightCacheInside.php
  src/ZM/Store/Lock/SpinLock.php
  src/ZM/Utils/CoMessage.php
  src/ZM/Utils/Manager/ProcessManager.php
  src/ZM/ZMServer.php
  src/ZM/global_functions.php
  zhamao
Labels: improvement, priority/medium

#126 添加 PHPStan 相关扩展
  composer.json
  phpstan.neon
  src/ZM/Container/ContainerTrait.php
  src/ZM/MySQL/MySQLStatement.php
Labels: improvement, priority/medium

#127 添加日志配置
  config/logging.php
  src/ZM/Event/SwooleEvent/OnWorkerStart.php
  src/ZM/global_functions.php
Labels: enhancement, priority/medium

#128 临时修复链接关闭容器错误
  src/ZM/Event/SwooleEvent/OnClose.php
Labels: bug, priority/medium

#131 轻量重构 Framework 类
  config/logging.php
  src/ZM/Framework.php
  src/ZM/global_functions.php
Labels: improvement, priority/medium

#129 优化容器服务注册
  src/ZM/Container/ContainerServicesProvider.php
  src/ZM/Event/SwooleEvent/OnClose.php
  src/ZM/Event/SwooleEvent/OnMessage.php
  src/ZM/Event/SwooleEvent/OnOpen.php
  src/ZM/Event/SwooleEvent/OnRequest.php
  src/ZM/Event/SwooleEvent/OnWorkerStart.php
  src/ZM/Event/SwooleEvent/OnWorkerStop.php
Labels: improvement, priority/low

#133 修复 OneBot11Adapter 无限回调溢出及其他小补丁
  config/logging.php
  src/Module/Example/Hello.php
  src/ZM/Adapters/AdapterInterface.php
  src/ZM/Adapters/OneBot11Adapter.php
  src/ZM/Container/ContainerServicesProvider.php
  src/ZM/Module/ModuleUnpacker.php
  src/ZM/global_functions.php
Labels: bug, improvement, priority/medium
