Repository zhamao-robot/zhamao-framework, pull requests merged in 2022-04, with the labels that each got.

#86 PHPStan 升级到 level 2
  .github/workflows/increment-build-number.yml
  .github/workflows/integration-test.yml
  phpstan.neon
  src/ZM/API/CQ.php
  src/ZM/API/CQAPI.php
  src/ZM/API/GoCqhttpAPIV11.php
  tests/ZM/API/CQTest.php
  tests/ZM/Utils/MessageUtilTest.php
Labels: help wanted, improvement, priority/medium

#87 API 文档重新生成并加入Workflow
  .github/workflows/increment-build-number.yml
  bin/gendoc
  docs/api/ZM/API/CQ.md
  docs/api/ZM/API/GoCqhttpAPIV11.md
  docs/api/ZM/API/OneBotV11.md
  docs/api/ZM/API/TuringAPI.md
  docs/api/ZM/Annotation/AnnotationParser.md
  docs/api/ZM/Annotation/Swoole/OnSwooleEventBase.md
  docs/api/ZM/Command/CheckConfigCommand.md
  docs/api/ZM/ConsoleApplication.md
  docs/api/ZM/Context/Context.md
  docs/api/ZM/DB/DB.md
  docs/api/ZM/DB/DeleteBody.md
  docs/api/ZM/DB/InsertBody.md
  docs/api/ZM/DB/SelectBody.md
  docs/api/ZM/DB/UpdateBody.md
  docs/api/ZM/Event/EventDispatcher.md
  docs/api/ZM/Event/EventManager.md
  docs/api/ZM/Event/SwooleEvent/OnTask.md
  docs/api/ZM/Framework.md
  docs/api/ZM/Http/Response.md
  docs/api/ZM/Module/ModulePacker.md
  docs/api/ZM/Module/ModuleUnpacker.md
  docs/api/ZM/Module/QQBot.md
  docs/api/ZM/MySQL/MySQLPool.md
  docs/api/ZM/MySQL/MySQLWrapper.md
  docs/api/ZM/Store/LightCache.md
  docs/api/ZM/Store/LightCacheInside.md
  docs/api/ZM/Store/Redis/ZMRedis.md
  docs/api/ZM/Store/ZMAtomic.md
  docs/api/ZM/Utils/CoMessage.md
  docs/api/ZM/Utils/DataProvider.md
  docs/api/ZM/Utils/HttpUtil.md
  docs/api/ZM/Utils/Manager/CronManager.md
  docs/api/ZM/Utils/Manager/ModuleManager.md
  docs/api/ZM/Utils/Manager/WorkerManager.md
  docs/api/ZM/Utils/MessageUtil.md
  docs/api/ZM/Utils/SignalListener.md
  docs/api/ZM/Utils/Terminal.md
  docs/api/ZM/Utils/ZMUtil.md
Labels: improvement, wip, priority/low

#89 更新 README Badges 及优化工作流触发路径
  .github/workflows/integration-test.yml
  .github/workflows/vuepress-deploy.yml
  README.md
Labels: enhancement, priority/low

#91 PHPStan Level 4
  phpstan.neon
  src/Module/Example/Hello.php
  src/ZM/API/CQ.php
  src/ZM/Annotation/AnnotationBase.php
  src/ZM/Annotation/AnnotationParser.php
  src/ZM/DB/DB.php
  src/ZM/DB/SelectBody.php
  src/ZM/Event/EventDispatcher.php
  src/ZM/Event/SwooleEvent/OnManagerStart.php
  src/ZM/Event/SwooleEvent/OnMessage.php
  src/ZM/Event/SwooleEvent/OnPipeMessage.php
  src/ZM/Event/SwooleEvent/OnWorkerStart.php
  src/ZM/Framework.php
  src/ZM/Http/StaticFileHandler.php
  src/ZM/MySQL/MySQLConnection.php
  src/ZM/Store/MySQL/SqlPoolStorage.php
  src/ZM/Utils/Terminal.php
  src/ZM/Utils/ZMUtil.php
  src/ZM/global_functions.php
Labels: improvement, priority/urgent

#96 实现 ZMRobot 内置 AllBots & AllGroups 代理类
  src/Module/Example/Hello.php
  src/ZM/API/Proxies/Bot/AbstractBotProxy.php
  src/ZM/API/Proxies/Bot/AllBotsProxy.php
  src/ZM/API/Proxies/Bot/AllGroupsProxy.php
  src/ZM/API/ZMRobot.php
  src/ZM/global_functions.php
Labels: enhancement, priority/medium

#97 增加 IoC 容器 & 依赖注入支持
  composer.json
  phpstan.neon
  src/Module/Example/Hello.php
  src/ZM/Container/BoundMethod.php
  src/ZM/Container/Container.php
  src/ZM/Container/ContainerInterface.php
  src/ZM/Container/EntryNotFoundException.php
  src/ZM/Container/EntryResolutionException.php
  src/ZM/Container/WorkerContainer.php
  src/ZM/Event/EventDispatcher.php
  src/ZM/Event/SwooleEvent/OnMessage.php
  src/ZM/Event/SwooleEvent/OnOpen.php
  src/ZM/Event/SwooleEvent/OnWorkerStart.php
  src/ZM/Event/SwooleEvent/OnWorkerStop.php
  src/ZM/Framework.php
  src/ZM/Store/ZMBuf.php
  src/ZM/Utils/DataProvider.php
  src/ZM/Utils/ReflectionUtil.php
  src/ZM/Utils/SingletonTrait.php
  src/ZM/global_functions.php
  tests/ZM/Container/ContainerCallTest.php
  tests/ZM/Container/ContainerTest.php
  tests/ZM/Container/WorkerContainerTest.php
Labels: enhancement, priority/medium

#99 增加全局助手函数
  src/ZM/global_functions.php
  tests/ZM/GlobalFunctionsTest.php
Labels: enhancement, priority/low

#102 重构 `match_pattern` 并添加测试
  src/ZM/global_functions.php
  tests/ZM/GlobalFunctionsTest.php
Labels: improvement, priority/urgent

#103 添加容器有序无名参数动态调用支持
  src/ZM/Container/BoundMethod.php
Labels: enhancement, priority/medium

#105 重构 RouteManager 静态文件路由数据存储
  src/ZM/Utils/Manager/RouteManager.php
Labels: improvement, priority/medium

#104 添加 HTTP 请求自动响应格式支持
  src/ZM/Event/SwooleEvent/OnRequest.php
Labels: enhancement, priority/medium

#107 PHPUnit 及部分结构优化
  bin/phpunit-swoole
  composer.json
  docs/update/build-update.md
  ext/lib/Printer.php
  ext/lib/Version.php
  phpstan.neon
  src/ZM/Event/SwooleEvent/OnWorkerStart.php
  src/ZM/Framework.php
  src/ZM/global_functions.php
  tests/ZM/GlobalFunctionsTest.php
Labels: improvement, priority/medium
