Repository zhamao-robot/zhamao-framework, pull requests merged in 2023-03, with the labels that each got.

#324 prompt 新增更新当前上下文绑定的事件对象的可选项
  src/Globals/global_defines_app.php
  src/ZM/Context/BotContext.php
Labels: enhancement

#323 修复 Phar 下入口文件的 Autoloader
  src/entry.php
Labels: bug

#326 中间件增强：支持传入参数
  src/Globals/global_class_alias.php
  src/ZM/Annotation/AnnotationParser.php
  src/ZM/Annotation/Middleware/Middleware.php
  src/ZM/Middleware/MiddlewareArgTrait.php
  src/ZM/Middleware/MiddlewareHandler.php
  src/ZM/Middleware/TimerMiddleware.php
Labels: improvement

#327 更新文档生成器的生成格式
  docs/components/common/class-alias.md
  src/ZM/Command/Generate/TextGenerateCommand.php
Labels: improvement

#330 文档更新：SQL 组件文档
  docs/.vuepress/config.js
  docs/components/store/mysql.md
Labels: documentation

#334 修复 BotContext 使用 reply 后无法激活其他回调的问题
  src/ZM/Context/BotContext.php
  src/ZM/Framework.php
Labels: bug

#335 修复 CommandArgument 在群组和讨论组中询问参数时未判断用户 ID 的 Bug
  src/ZM/Plugin/OneBot/OneBot12Adapter.php
Labels: bug

#338 修复 BotActionResponse 注解事件不支持 status 限定的 Bug
  src/ZM/Annotation/OneBot/BotActionResponse.php
  src/ZM/Framework.php
  src/ZM/Plugin/OneBot/OneBot12Adapter.php
Labels: bug

#337 文档更新：部分内容调整补充、WebSocket 客户端接入
  docs/.vuepress/config.js
  docs/components/common/global-defines.md
  docs/components/common/hot-update.md
  docs/components/container/dependencies.md
  docs/components/http/websocket-access.md
  docs/components/http/websocket-client.md
  docs/components/store/redis.md
  docs/event/bot.md
  src/Globals/global_class_alias.php
Labels: documentation

#342 修复 Symfony Console Event Dispatcher 接口缺失
  src/ZM/ConsoleApplication.php
Labels: bug

#343 添加 RuntimePreferences 配置目录回退
  config/config.php
  src/ZM/Config/RuntimePreferences.php
Labels: bug, improvement

#346 插件文档更新，助手函数添加
  docs/advanced/custom-start.md
  docs/components/common/global-defines.md
  docs/components/store/file-system.md
  docs/guide/structure.md
  docs/plugins/develop.md
  docs/plugins/management.md
  src/Globals/global_functions.php
  src/ZM/Framework.php
  src/ZM/Plugin/PluginManager.php
  src/ZM/Plugin/PluginMeta.php
Labels: documentation
