Repository zhamao-robot/zhamao-framework, pull requests merged in 2023-02, with the labels that each got.

#279 添加容器缓存配置
  config/container.php
  src/ZM/Container/ContainerHolder.php
  tests/ZM/Event/Listener/HttpEventListenerTest.php
Labels: enhancement

#280 添加依赖注入组件文档
  .gitignore
  docs/.vuepress/config.js
  docs/components/container/configuration.md
  docs/components/container/dependencies.md
  docs/components/container/dependency-injection.md
  package.json
Labels: documentation

#281 修复 Pipeline 回调参数缺失
  src/ZM/Middleware/MiddlewareHandler.php
Labels: bug

#282 修复中间件传参解析冲突
  src/Module/Example/Hello123.php
  src/ZM/Middleware/MiddlewareHandler.php
  src/ZM/Plugin/OneBot12Adapter.php
Labels: bug

#283 新增计时器
  docs/components/common/class-alias.md
  src/Globals/global_class_alias.php
  src/Globals/global_functions.php
  src/ZM/Annotation/AnnotationParser.php
  src/ZM/Annotation/Framework/Tick.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Framework.php
  src/ZM/Plugin/PluginManager.php
  src/ZM/Plugin/Traits/TickTrait.php
  src/ZM/Plugin/ZMPlugin.php
  src/ZM/Schedule/Timer.php
Labels: enhancement

#286 修复排程任务 Swoole 死锁
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Framework.php
  src/ZM/Schedule/Schedule.php
Labels: bug

#288 文档更新
  docs/event/bot.md
  docs/guide/get-started.md
  docs/guide/installation.md
  docs/update/v3.md
Labels: documentation

#295 修复初始化命令兼容性问题
  src/ZM/Command/InitCommand.php
Labels: bug

#296 修复安装脚本不使用内置 Composer
  ext/v3.sh
Labels: bug

#297 修复插件安装命令若干问题
  src/ZM/Command/Plugin/PluginInstallCommand.php
Labels: bug

#298 修复排程任务不支持提醒
  src/ZM/Schedule/Schedule.php
Labels: improvement

#300 修复多次调用 prompt() 超时时间出现错乱的 Bug
  docs/update/v3.md
  src/ZM/Context/BotContext.php
  src/ZM/Framework.php
  src/ZM/Schedule/Timer.php
Labels: bug

#303 修复 Workerman CtrlC 退出时会弹出假的 Fatal Error 的 Bug
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Utils/CodeGenerator/PluginGenerator.php
Labels: bug

#304 修复 BotCommand 使用 regex 时参数错乱的 Bug
  src/ZM/Plugin/OneBot12Adapter.php
Labels: bug

#305 修复使用 Route 注解时无法自定义响应包体的 Bug
  src/ZM/Event/Listener/HttpEventListener.php
Labels: bug

#306 修复使用内建 Composer 时无法生成 psr4 插件的 Bug
  src/ZM/Command/InitCommand.php
  src/ZM/ConsoleApplication.php
Labels: bug

#307 文档更新：新增插件市场
  docs/.vuepress/components/PluginList.vue
  docs/.vuepress/components/plugin_list.js
  docs/.vuepress/config.js
  docs/README.md
  docs/plugin-market/README.md
Labels: documentation

#310 添加 InvalidDefinition 解决方案提示
  src/Module/Example/Hello123.php
  src/ZM/Exception/Solution/SolutionRepository.php
Labels: enhancement

#318 更新 GH Action
  .github/workflows/build-release-artifacts.yml
  .github/workflows/increment-build-number.yml
  composer.json
  src/ZM/Command/BuildCommand.php
  src/ZM/Command/Generate/TextGenerateCommand.php
Labels: workflow

#319 添加构建命令开发依赖检测
  src/Globals/global_defines_app.php
  src/Globals/global_defines_framework.php
  src/ZM/Command/BuildCommand.php
  src/ZM/Command/Command.php
  src/ZM/Command/CommandInteractTrait.php
  src/ZM/Framework.php
Labels: enhancement

#320 提前 Bootstrapers 调用时机
  bin/phpunit-zm
  config/config.php
  src/ZM/Bootstrap/RegisterLogger.php
  src/ZM/Config/ZMConfig.php
  src/ZM/ConsoleApplication.php
  src/ZM/Framework.php
Labels: improvement
