Repository zhamao-robot/zhamao-framework, pull requests merged in 2023-01, with the labels that each got.

#226 添加 Phar 构建命令
  bin/zhamao
  bin/zhamao.bat
  src/ZM/Command/BuildCommand.php
  src/ZM/Command/Command.php
  zhamao
Labels: enhancement

#227 update v3.sh update script
  ext/v3.sh
Labels: improvement

#229 重构注解解析器和优化部分代码
  composer.json
  docs/guide/installation.md
  ext/v3.sh
  src/Globals/script_setup_loader.php
  src/ZM/Annotation/AnnotationMap.php
  src/ZM/Annotation/AnnotationParser.php
  src/ZM/Annotation/Framework/Init.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Framework.php
  src/ZM/Plugin/OneBot12Adapter.php
  src/ZM/Plugin/PluginManager.php
Labels: improvement

#230 新增 Redis 支持
  config/global.php
  src/Globals/global_class_alias.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Framework.php
  src/ZM/Store/Database/DBPool.php
  src/ZM/Store/KV/Redis/KVRedis.php
  src/ZM/Store/KV/Redis/RedisException.php
  src/ZM/Store/KV/Redis/RedisPool.php
  src/ZM/Store/KV/Redis/ZMRedis.php
Labels: enhancement

#231 修复 Route 注解无法正常解析的 Bug
  src/ZM/Event/Listener/HttpEventListener.php
Labels: bug

#232 添加定时任务支持
  src/Module/Example/Hello123.php
  src/ZM/Annotation/AnnotationParser.php
  src/ZM/Annotation/Framework/Cron.php
  src/ZM/Schedule/Schedule.php
Labels: enhancement

#233 修复测试结果输出错误
  tests/ZMResultPrinter.php
Labels: bug

#234 暂时停用网络请求测试并修复文件系统测试
  src/ZM/Store/FileSystem.php
  tests/ZM/Store/FileSystemTest.php
  tests/ZM/Utils/ZMRequestTest.php
Labels: bug

#235 修复一些小问题和添加 GitAttributes
  .gitattributes
  .github/workflows/coding-style.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  bin/prepare-doxygen
  src/ZM/Event/Listener/WorkerEventListener.php
Labels: improvement

#238 修复 Doxygen 权限
  bin/prepare-doxygen
Labels: bug

#237 更新首页介绍
  README.md
Labels: documentation

#236 增加 PostgreSQL 支持
  src/ZM/Framework.php
  src/ZM/Store/Database/DBPool.php
  src/ZM/Store/Database/DBWrapper.php
  src/ZM/Store/Database/PgSQLDriver.php
Labels: enhancement

#239 修复 Doxygen Sudo 权限
  bin/prepare-doxygen
Labels: bug

#240 Beta5 系列升级内容（包含 Redis、sendAction 协程、reply 模式、修复 data 报错）
  src/Globals/global_defines_app.php
  src/Globals/global_functions.php
  src/ZM/Context/BotContext.php
  src/ZM/Context/Trait/BotActionTrait.php
  src/ZM/Plugin/OneBot12Adapter.php
  src/ZM/Store/KV/Redis/RedisWrapper.php
Labels: bug, enhancement, improvement

#241 重构新的 waitMessage 到 prompt
  src/ZM/Context/BotContext.php
  src/ZM/Plugin/OneBot12Adapter.php
Labels: enhancement

#243 文档更新 - 机器人上下文
  .editorconfig
  composer.json
  docs/.vuepress/components/ChatBox.vue
  docs/.vuepress/config.js
  docs/components/bot/bot-context.md
  docs/components/bot/message-segment.md
  docs/guide/README.md
  docs/guide/configuration.md
  docs/guide/get_started.md
  docs/guide/installation.md
Labels: documentation

#244 更新版权所有年份
  LICENSE
  docs/README.md
Labels: documentation

#246 更新部分文档和新增有关生成器
  docs/.vuepress/config.js
  docs/components/bot/bot-context.md
  docs/components/bot/message-segment.md
  docs/components/common/class-alias.md
  src/Globals/global_class_alias.php
  src/ZM/Command/Generate/TextGenerateCommand.php
Labels: documentation

#248 新增 prompt 方法的选项参数
  src/Globals/global_defines_app.php
  src/ZM/Context/BotContext.php
  src/ZM/Exception/WaitTimeoutException.php
  src/ZM/Framework.php
  src/ZM/Plugin/OneBot12Adapter.php
Labels: enhancement

#249 优化 ZMRequest POST 数据时允许直接传入数组
  src/ZM/Utils/ZMRequest.php
Labels: improvement

#250 删除 Context
  .phpstorm.meta.php
  config/global.php
  src/ZM/Container/ContainerRegistrant.php
  src/ZM/Context/Context.php
Labels: improvement

#251 更新 BotContext 和 FileSystem 文档
  docs/.vuepress/config.js
  docs/components/bot/bot-context.md
  docs/components/store/file-system.md
Labels: documentation

#252 文档更新：全局常量和方法
  docs/.vuepress/config.js
  docs/components/common/global-defines.md
Labels: documentation

#255 添加环境变量支持
  composer.json
  config/container.php
  config/global.php
  src/Globals/global_functions.php
  src/ZM/Bootstrap/LoadConfiguration.php
  src/ZM/Config/Environment.php
  src/ZM/Config/EnvironmentInterface.php
Labels: enhancement

#254 重构插件加载器、BotContext、AnnotationMap 新增方法、修复部分 Bug
  config/global.php
  docs/update/v3.md
  src/Globals/global_defines_app.php
  src/Globals/global_functions.php
  src/Globals/script_setup_loader.php
  src/ZM/Annotation/AnnotationMap.php
  src/ZM/Annotation/Framework/Cron.php
  src/ZM/Annotation/OneBot/BotAction.php
  src/ZM/Command/Generate/TextGenerateCommand.php
  src/ZM/Command/Plugin/PluginPackCommand.php
  src/ZM/Container/ContainerRegistrant.php
  src/ZM/Context/Trait/BotActionTrait.php
  src/ZM/Event/Listener/WorkerEventListener.php
  src/ZM/Plugin/CommandManual/CommandManualPlugin.php
  src/ZM/Plugin/OneBot12Adapter.php
  src/ZM/Plugin/PluginManager.php
  src/ZM/Plugin/PluginMeta.php
  src/ZM/Plugin/Traits/BotActionTrait.php
  src/ZM/Plugin/Traits/BotCommandTrait.php
  src/ZM/Plugin/Traits/BotEventTrait.php
  src/ZM/Plugin/Traits/CronTrait.php
  src/ZM/Plugin/Traits/EventTrait.php
  src/ZM/Plugin/Traits/InitTrait.php
  src/ZM/Plugin/Traits/PluginLoadTrait.php
  src/ZM/Plugin/Traits/RouteTrait.php
  src/ZM/Plugin/ZMPlugin.php
  src/ZM/Store/KV/KVInterface.php
  src/ZM/Store/KV/LightCache.php
  src/ZM/Store/KV/Redis/KVRedis.php
  src/ZM/ZMApplication.php
Labels: improvement

#258 添加机器人接入鉴权文档
  docs/.vuepress/config.js
  docs/components/bot/authorization.md
Labels: documentation

#260 添加日志记录及调试文档
  docs/.vuepress/config.js
  docs/components/common/logging.md
  docs/guide/debugging.md
Labels: documentation

#263 添加 ZMRequest 文档
  docs/.vuepress/config.js
  docs/components/http/zmrequest.md
Labels: documentation

#262 添加 Redis 数据库文档
  docs/.vuepress/config.js
  docs/components/common/global-defines.md
  docs/components/store/redis.md
Labels: documentation

#264 修复 Cron 使用闭包方法导致错误的 Bug
  src/ZM/Schedule/Schedule.php
Labels: bug

#265 新增 WebSocket Frame 对象的依赖注入
  src/ZM/Container/ContainerRegistrant.php
Labels: enhancement

#266 新增 ZMRequest 的类别名
  docs/components/common/class-alias.md
  src/Globals/global_class_alias.php
  src/ZM/Command/Generate/TextGenerateCommand.php
Labels: enhancement

#269 新增动态 Token 鉴权功能
  src/ZM/Framework.php
  src/ZM/Plugin/OneBot12Adapter.php
Labels: enhancement
